### ISSUE TITLE
pool.js error on node init.js (first run)

### ISSUE THREAD

**Issue by sigwo** [dbeal-eth/node-merged-pool#1]
I just pulled this into my working NOMP installation. I rm -rf'ed node_modules/stratum-pool, and git pull while in the node_modules folder. npm update from the stratum-pool folder. No errors from that. Went to my screen session, node init.js2014-08-20 22:07:37 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...

2014-08-20 22:10:56 [POSIX]     [Connection Limit](Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2014-08-20 22:10:56 [Master]    [CLI] CLI listening on port 17117
2014-08-20 22:10:57 [Master]    [PoolSpawner] Spawned 7 pool(s) on 2 thread(s)
2014-08-20 22:10:58 [Website]   [Server] Website started on 0.0.0.0:80

/var/www/nomp/node_modules/stratum-pool/lib/pool.js:453
        for(var i = 0;i < options.auxes.length;i++) {
                                       ^
TypeError: Cannot read property 'length' of undefined
    at SetupDaemonInterfaces (/var/www/nomp/node_modules/stratum-pool/lib/pool.js:453:40)
    at pool.start (/var/www/nomp/node_modules/stratum-pool/lib/pool.js:42:9)
    at createAndStartPool (/var/www/nomp/libs/poolWorker.js:224:14)
    at /var/www/nomp/libs/poolWorker.js:229:9
    at Array.forEach (native)
    at new module.exports (/var/www/nomp/libs/poolWorker.js:228:30)
    at Object.<anonymous> (/var/www/nomp/init.js:74:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
2014-08-20 22:10:59 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
2014-08-20 22:10:59 [Payments]  [cannabiscoin] Payment processing setup to run every 120 second(s) with daemon (CannabisCoinrpc@127.0.0.1:39347) and redis (127.0.0.1:6379)
2014-08-20 22:10:59 [Payments]  [cryptcoin] Payment processing setup to run every 120 second(s) with daemon (cryptcoinrpc@127.0.0.1:27115) and redis (127.0.0.1:6379)
2014-08-20 22:10:59 [Payments]  [diamond] Payment processing setup to run every 120 second(s) with daemon (bitcoinrpc@127.0.0.1:17772) and redis (127.0.0.1:6379)
2014-08-20 22:10:59 [Payments]  [goldcoin] Payment processing setup to run every 120 second(s) with daemon (ticky@127.0.0.1:8122) and redis (127.0.0.1:6379)
2014-08-20 22:10:59 [Payments]  [potcoin] Payment processing setup to run every 120 second(s) with daemon (tricky@127.0.0.1:42000) and redis (127.0.0.1:6379)
2014-08-20 22:10:59 [Payments]  [smartcoin] Payment processing setup to run every 120 second(s) with daemon (tricky@127.0.0.1:58583) and redis (127.0.0.1:6379)
2014-08-20 22:10:59 [Payments]  [syscoin] Payment processing setup to run every 120 second(s) with daemon (syscoinrpc@127.0.0.1:8368) and redis (127.0.0.1:6379)
2014-08-20 22:10:59 [Payments]  [cannabiscoin] Finished interval - time spent: 36ms total, 4ms redis, 14ms daemon RPC
2014-08-20 22:10:59 [Payments]  [cryptcoin] Finished interval - time spent: 36ms total, 3ms redis, 13ms daemon RPC
2014-08-20 22:10:59 [Payments]  [diamond] Finished interval - time spent: 36ms total, 1ms redis, 12ms daemon RPC
2014-08-20 22:10:59 [Payments]  [goldcoin] Finished interval - time spent: 37ms total, 1ms redis, 16ms daemon RPC
2014-08-20 22:10:59 [Payments]  [potcoin] Finished interval - time spent: 37ms total, 3ms redis, 19ms daemon RPC
2014-08-20 22:10:59 [Payments]  [smartcoin] Finished interval - time spent: 38ms total, 0ms redis, 19ms daemon RPC

/var/www/nomp/node_modules/stratum-pool/lib/pool.js:453
        for(var i = 0;i < options.auxes.length;i++) {
                                       ^
2014-08-20 22:10:59 [Payments]  [syscoin] Finished interval - time spent: 4ms total, 2ms redis, 3ms daemon RPC
TypeError: Cannot read property 'length' of undefined
    at SetupDaemonInterfaces (/var/www/nomp/node_modules/stratum-pool/lib/pool.js:453:40)
    at pool.start (/var/www/nomp/node_modules/stratum-pool/lib/pool.js:42:9)
    at createAndStartPool (/var/www/nomp/libs/poolWorker.js:224:14)
    at /var/www/nomp/libs/poolWorker.js:229:9
    at Array.forEach (native)
    at new module.exports (/var/www/nomp/libs/poolWorker.js:228:30)
    at Object.<anonymous> (/var/www/nomp/init.js:74:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
2014-08-20 22:10:59 [Master]    [PoolSpawner] Fork 1 died, spawning replacement worker...

**Comment by sigwo** [comment]
Sooo, I guess I should read slower than the speed of light. I'll read the example.js like you told me too.
