### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by jjj092353** [dbeal-eth/node-merged-pool#3]
Killbyte - wondered if you'd be interested in helping me get all this up and running for some BTC - I want to setup a merged mining pool with Doge, Ltc, Sys, 42 and Pot

**Comment by sigwo** [comment]
I have it working and finding blocks for POT and SYS. LTC is running, but I do not have enough hash to solve a LTC block. DOGE is waiting for the AUXPoW block but works on testnet. My issue is when I find a block, the stratum throws an error and crashes. I've been working on it in my spare time, as I currently have a commissioned project taking up time.  Payouts do not currently work, but I only have me and a friend mining, so I just manually pay her. :) You can check it out at http://bemining.net if you like.

**Comment by jacobnollette** [comment]
How did you guys get your private keys setup? https://github.com/KillerByte/node-merged-pool/issues/4

**Comment by sigwo** [comment]
Private key? Use addie.cc for the username for miners and add the addresses
to that profile. I'm not sure what private keys you are talking about...For
the pools/*coin.json, setup the local wallet address in the file.

**Comment by jacobnollette** [comment]
you must have modified from the demo some — in the config file it requires one single address for generating coins, shared across all coins... How did you share a private key across multiple coins?

**Comment by sigwo** [comment]
It's a public key. I generated it from my NOMP pool. Try visiting
http://judge.bemining.net/mining_key and you can download the standalone
version.

**Comment by jacobnollette** [comment]
gotcha, i'm familiar with nomp, have an instance running locally... had wondered about that.. thanks for the input... BTW whats with waiting for the AUXPow block (doge), shouldn't merged mining just work now?

**Comment by sigwo** [comment]
No, they aren't to the block that signals the AUXPoW yet.

**Comment by jacobnollette** [comment]
sigwo — i'm confused, so i tried adding the mining private address as the primary coin payout address — server is saying address is invalid — how do I add the addresses for all the merged coins then?

**Comment by jacobnollette** [comment]
I'm live now.., we'll see about the crash you mentioned.

How are you merge mining potcoin?? Api throwing an error for getauxblock

**Comment by sigwo** [comment]
POT is the main coin and syscoin is the AUXPoW coin.

**Comment by sigwo** [comment]
You can merge mine any scrypt coin with SYS.

**Comment by jacobnollette** [comment]
what are you doing to keep the process running after it crashes on successful block? cron?

**Comment by sigwo** [comment]
I haven't fixed the block crash or the restart. I'm monitoring the hashrate every so often. As I said, it is an experimental pool now. I'm actually moving it to a different server so I can restart my big NOMP instance and not have it effect testing.

**Comment by sigwo** [comment]
nothing right now. LOL I see in the logs where it errors, so I'm trying to
fix it rather than band-aid it.

**Comment by jacobnollette** [comment]
i will try to dig in later.. i was using node forever to keep it persistent, but wasn't getting any blocks for hours, and wondered if something was going wrong somewhere down the line... Hard to tell.

**Comment by sigwo** [comment]
I think the stratum dies, not the server and that's why forever or a cron
won't work. I ran just the barebones node-merged-pool (not portal) and it
crashes after finding a block. It's not the portal, but the stratum that
has an error.

And the payouts are a whole different ballgame. Really wishing the creator
would stop by :-)

**Comment by jjj092353** [comment]
seems like too many problme here to even attempt implementing - however I have one question: 

you wrote: You can merge mine any scrypt coin with SYS.

is this true? I thought one certain coins could be merged mined - not "any' coin as your state (at least with sys) which is kind of tanking right now.

**Comment by sigwo** [comment]
As long as the difficulty is higher than the aux coin (SYS, in this case),
yes. Any scrypt coin. LTC is the preferred choice because the diff is so
high on LTC.

**Comment by sigwo** [comment]
But even then you can. I am merge mining POT/SYS, RBY/SYS, and VIA/SYS
right now. I have found several POT blocks, which is a lower diff coin than
SYS. I just won't (shouldn't) find any SYS blocks right now.

**Comment by jjj092353** [comment]
what do you have as a Primary coin?

**Comment by sigwo** [comment]
POT, RBY, and VIA

**Comment by jjj092353** [comment]
so - you are just merge mining two coins and have been using either POT, RBY or VIA as your primary coin?

**Comment by sigwo** [comment]
Yes. There are very few coins that can be the secondary coin. DOGE is the
biggest that will be merge-able when they get to block 371337.

**Comment by jjj092353** [comment]
so - let me get this right - if I have POT, SYS, RBY, VIA or 42 as a primary - I can mine any other scrypt coin as a secondary?

**Comment by sigwo** [comment]
No. The primary coin is not the merge mineable coin. doge / sys / taco / peseta / huntercoin(broken) / united scrypt coin / umbrella / Monocle / Parrallax are the merge mineable coins that are the SECONDARY coins. ANY scrypt coin can be the MAIN coin. It is only beneficial (attempting to solve blocks on both chains) IF the MAIN coin has a HIGHER difficulty than the SECONDARY coin.

**Comment by BigMcRat** [comment]
hi guys,

did you know how to configure pool.json to mine on two or more AuxPow Coins?

**Comment by sigwo** [comment]
Doesn't work afaik. 

-SG

**Comment by BigMcRat** [comment]
Hi sigwo,

do you mean two or more AuxPOW coins do not work together or is not possible to mine more AuxPow Coins with this stratum?

**Comment by sigwo** [comment]
It works using more than one AUXPoW coin together, just not with this software. 

-SG

**Comment by BigMcRat** [comment]
Hi sigwo,

Thanks a lot for your help!
can you suggest a good software for mining more than one AuxPOW coins?

**Comment by sigwo** [comment]
https://github.com/simplecrypto/powerpool

-SG

**Comment by microlost** [comment]
hi,sigwo,the portal of your pool (http://bemining.net) looks nice,where is the souce?
I now I want to build a merged pool mining LTC & DOGE,what do you think of what software should I use

**Comment by sigwo** [comment]
I have forked UNOMP to https://github.com/sigwo/unified-node-open-mining-portal.

**Comment by microlost** [comment]
thanks,does your fork suitable for a merged pool?

**Comment by sigwo** [comment]
It works as intended EXCEPT does NOT pay merged coins to miners yet. Also I have reports that merged mining doesn't work for some. I'm actively working on this project. Only use in testing scenarios at the moment. There are a couple that use this in MPOS mode as well, so the testing base is good.

**Comment by microlost** [comment]
so,you means can't be build a merged pool with this project now.
I have also notice the powerpool your suggested above,and  try for a couple hours,but I got an error like this: https://github.com/simplecrypto/powerpool/issues/126

Do you know what is the problem

**Comment by sigwo** [comment]
So, there are two parts to mining pools. The stratum and the portal (or website). This is the [stratum](https://github.com/sigwo/node-merged-pool) that I use to build UNOMP. My above link is to the portal, that pulls in the stratum together, into a working unit. My UNOMP link is a working pool, albeit an alpha, in development, project.

**Comment by microlost** [comment]
I have try with your fork UNOMP,the backenk work well,but when I run the frontend,I got a error like this:
module.js:340
    throw err;
          ^
Error: Cannot find module 'log4js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/unomp/init.js:9:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by sigwo** [comment]
Install log4js

-SG

**Comment by microlost** [comment]
now error like this after install log4js:

[2015-03-29 17:22:44.379] [INFO] [default] - New Relic
[2015-03-29 17:22:44.388] [INFO] [default] - POSIX Not Installed
[2015-03-29 17:22:44.388] [DEBUG] [default] - POSIX Connection Limit (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
[2015-03-29 17:22:44.388] [INFO] [default] - Run Workers
[2015-03-29 17:22:44.406] [DEBUG] [default] - Master CLI CLI listening on port 17117
[2015-03-29 17:22:44.910] [DEBUG] [default] - Master PoolSpawner Spawned 1 pool(s) on 2 thread(s)
[2015-03-29 17:22:45.352] [INFO] [default] - New Relic
[2015-03-29 17:22:45.371] [INFO] [default] - POSIX Not Installed
[2015-03-29 17:22:45.372] [INFO] [default] - Run Workers
[2015-03-29 17:22:45.474] [DEBUG] [default] - Website Server Website started on 0.0.0.0:8080
[2015-03-29 17:22:45.720] [INFO] [default] - New Relic
[2015-03-29 17:22:45.747] [INFO] [default] - POSIX Not Installed
[2015-03-29 17:22:45.749] [INFO] [default] - Run Workers
[2015-03-29 17:22:45.791] [DEBUG] [default] - Switching Setup Thread 1 Loading last proxy state from redis
[2015-03-29 17:22:45.819] [DEBUG] [default] - Pool litecoin Thread 1 Share processing setup with redis (127.0.0.1:6379)
[2015-03-29 17:22:45.841] [DEBUG] [default] - Switching Setup Thread 1 Last proxy state loaded from redis
[2015-03-29 17:22:45.861] [DEBUG] [default] - Switching Setup Thread 1 Switching "switch2" listening for scrypt on port 4444 into litecoin

/root/unomp/libs/poolWorker.js:225
            logger[severity](logSystem, logComponent, logSubCat, text);
                            ^
TypeError: Object #<Logger> has no method 'special'
    at pool.on.on.on.on.process.send.type (/root/unomp/libs/poolWorker.js:225:29)
    at pool.emit (events.js:98:17)
    at emitSpecialLog (/root/unomp/node_modules/merged-pool/lib/pool.js:28:49)
    at OutputPoolInfo (/root/unomp/node_modules/merged-pool/lib/pool.js:133:9)
    at /root/unomp/node_modules/merged-pool/lib/pool.js:51:29
    at StratumServer.StartStratumServer._this.stratumServer.on.on.on.client.on.on.extraNonce2Size (/root/unomp/node_modules/merged-pool/lib/pool.js:573:13)
    at StratumServer.emit (events.js:92:17)
    at Server.<anonymous> (/root/unomp/node_modules/merged-pool/lib/stratum.js:439:27)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:117:20)
[2015-03-29 17:22:45.935] [ERROR] [default] - Master PoolSpawner Fork 0 died, spawning replacement worker...

**Comment by sigwo** [comment]
oh, no wonder LOL. This isn't my repo.You never changed to the repo i linked above.....

**Comment by microlost** [comment]
Indeed, very embarrassed...LOL..., wasted me a couple of days
I have rebuild it with your repo, and it works now ,thanks.
my pool  now have found a LTC block and couples of DOGE blocks,but always in a pending state,also ,the pool can't pay to workers, Neither LTC nor DOGE.
Then I want to set the confirmations of block number, but there is no relative options in the config file.
Are you still in the development of this software?

**Comment by sigwo** [comment]
Go here https://github.com/UNOMP/unified-node-open-mining-portal
That is the current software development effort.

**Comment by microlost** [comment]
that was the repo I have try before

**Comment by sigwo** [comment]
This repo does nothing but the stratum. If you are looking for something that looks like http://pool.unomp.org, go to the linked repo in my last reply. If not, I cannot help, as I do not own this repo.

**Comment by microlost** [comment]
you said above that your rope can NOT pay merged coins to miners yet,does it means neither primary coin nor AUXPoW coin?

**Comment by microlost** [comment]
you said above that your rope can NOT pay merged coins to miners yet,does it means neither primary coin nor AUXPoW coin?

**Comment by sigwo** [comment]
Please move to the current repo. I cannot fix/change anything in this repo. Please create tickets for issues in the following repo:
https://github.com/UNOMP/unified-node-open-mining-portal

I will no longer respond to this thread. I hope to see you in the new repo.

**Comment by microlost** [comment]
ok, thanks.

**Comment by huzhen-v5** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
bettimax0, @Shinshin100, @Bossjkie, @ArtDental, @vintnee, @Truman78es, @HeziTech, @pensadorramm, @PawlowskiAdrian, @snapfractalpop, @Fannysmpth, @niuhb, @lthoya52-cpu, @xunux, @jaredrummler, @DokCis, @yojoey69, @qwertyguise, @itworkco, @hamedhub
